apiVersion: v1
kind: Service
metadata:
  name: http2-service
spec:
  selector:
    app: http2-backend
  ports:
    - name: http-port
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: http2-port
      protocol: TCP
      port: 3001
      targetPort: 3001
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-c
  labels:
    account: details # TODO: what's this?
---
apiVersion: v1
kind: Secret
metadata:
  name: service-c-secret
type: Opaque
data:
  server.crt: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3RENDQWFnQ0NRRFdoS1c4SVl2a2VUQU5CZ2txaGtpRzl3MEJBUXNGQURBaU1Rc3dDUVlEVlFRR0V3SlYKVXpFVE1CRUdBMVVFQ0F3S1EyRnNhV1p2Y201cFlUQWVGdzB5TVRBek1ERXlNak13TWpWYUZ3MHlNakF6TURFeQpNak13TWpWYU1DSXhDekFKQmdOVkJBWVRBbFZUTVJNd0VRWURWUVFJREFwRFlXeHBabTl5Ym1saE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXNzRDNQclN3MEdhSmdFK0R4WXBEbjBXMS9GVG0KUURnUEQ5bndyT3BZRXpuQjZJNFVTNm9qS0hBQjZJckdFbDBDdDdDckMzaGpRV2VkUjEwYzMxd0VQb1ZGdXNnUgp0NnB0VWtBZHhzL0o4T3lsY3RkZmpLZUFvQUczZ0NkdFdOcVdiMnpOT1pYVGtYZVRHNG5iaTlUZDFIdjlBRWR3CkxCa2psaGNKQ1YxYUExaytud0hET2pOeGluWTF0MWFtaTZBaWdkaTFGNFhNWDZLV1Ixd3dIT09jdEJvU0QzSTEKNjRUdExIbVN4UHIvWkxSRGI3RnVXUzVYRC95M1ROVXc0ZXVkSHd4c01QbDN5RWFWM2VURUhRYWtLOTRpaTRFSgpUNHNjcERkOFBZNHk4VVhYUVU5MFgwdUJoZVZDVnc1YlNlMmw3eW9ZNEYrNzdhaWY1TkFUcExDMlV3SURBUUFCCk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ05Zb1RrN1E5Z1UzSWZna05XOEV4YnBCRUV3dnFtWllkcGo5UmUKRlpNdEZ6dFloYTFIaXlOclBYdHNnb2ZveVZtNzJwMlBtNkp3TjZIODFRSDhWZGwyTi9mTXg4dnRoOWJsdkFGcgpQMFA1R2NJemhoQStHdjhaMDJZRk5hclZxVlpKTUJtaEtWQWJPVXBKVGtBTllpckZWMFF0UjFidUV4aU1LaUN5ClByL2NyVWFOaEY0TEJFYUhPU0dDU0dNSlVRdVlSdnYyTGc4b0ZsTU1EdHlrZENYRmEySGdPaGNYdkxFMTFVc3EKbytDTlRYdXIvYXJVejFDRS9xU0ZBTVBDVXJVeWp1UWR3cFMwMVIrdGprOWpneE40MWJtUEZCOFVCUElQUzhLSgp4amgzQk1KdURrem1xNDVEZEQzcllhVkd0dGJ3YVlQQ2xzend2Ky9MZCszbHRpQloKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  server.key: >-
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBc3NEM1ByU3cwR2FKZ0UrRHhZcERuMFcxL0ZUbVFEZ1BEOW53ck9wWUV6bkI2STRVClM2b2pLSEFCNklyR0VsMEN0N0NyQzNoalFXZWRSMTBjMzF3RVBvVkZ1c2dSdDZwdFVrQWR4cy9KOE95bGN0ZGYKaktlQW9BRzNnQ2R0V05xV2Iyek5PWlhUa1hlVEc0bmJpOVRkMUh2OUFFZHdMQmtqbGhjSkNWMWFBMWsrbndIRApPak54aW5ZMXQxYW1pNkFpZ2RpMUY0WE1YNktXUjF3d0hPT2N0Qm9TRDNJMTY0VHRMSG1TeFByL1pMUkRiN0Z1CldTNVhEL3kzVE5VdzRldWRId3hzTVBsM3lFYVYzZVRFSFFha0s5NGlpNEVKVDRzY3BEZDhQWTR5OFVYWFFVOTAKWDB1QmhlVkNWdzViU2UybDd5b1k0Ris3N2FpZjVOQVRwTEMyVXdJREFRQUJBb0lCQUZCVzJBalB6elFyRVp1ZwpvVG5VZGFZTS84a0VJMlF6amRseSsyL0w5My9Va3FsQnlpOWpyVitNVDk5REY5akRBdWlxTjRYMU9xNzNzY0dVClFOakdrNFhDQWwvN2NiTVpudjY3b0dadGwzWjM5YmhTd2pnR1JKSWxrMksrMWE5OHR1WW5nV2xqUkc1NXpwMHUKN1lUQVRGOG14c1FzVjJjS2VXc0l1V0FERytTcXBHY0lCTHEyT3diN3VFQWF2Q1g1MlkwUUFMN1M4Q3NXb2RucAp1bnh4MU9hTFkvVUNBL0JsNlNUZXNlOVg4NTZPWURTekgrWmZYcHd3WHZSUDNrYUdaYzcxNjIvUzhoTWY2ME9sCnY3a1dqbGdDTjlOUFI1a0g1SW9OOU1sUlFSdUE1dGxwUUdySE80eXg2TEtYSGlRYTJPVURyQzJhNnNId2FaWTMKUkdPVnhXRUNnWUVBMW9IMlVkbTJZNFQrTU53SjhEbS82ZkYxRmFXLzJvT01ramNpUk9adk5NNGpTS1VJU2M3VQpyUDVMTVE0NHNyTmdEajFIN25rVWlZZjVPZ2pCMVc5WjNaQ21oRFJUV0tST3VPVWpBU3M0NnZQZHgxalY2bSs1Ck9BZGlwZ1J4anNOcFp4U3dJMmRHWWlNQ2huSGZ4Qk9zVmtZMUt1OXdEMGg4bTZLeHRWa1k0MUVDZ1lFQTFWU0kKMVUrYUQwVmk0M21sSzFVUXlHNDhqSHRQYkRBK3JzRVlwMjJvbWpNb0xMV2VnVEtlSkdWK1Y3ZjZDNkF5MWVmYgpIVnNtRjZkbDFvVFRwM1VpMWk5aEdMUVZJckhSVnh6OWtBWXFLeFlWVnBxNEJ5TElFU1djREx0cERRWURBYnR4CnYrdTFKS0xySzNPU2FXWUg1OWd5ZzRnM0FBZXh0WXVMR1Zja2JtTUNnWUI1MFVCelp6SSsvaTNrelhFUGJaeGgKWFBCakpNZjViaStNY2FjU2ZkSzFxRU05WkF0Njd1eTBlWTEyQkYrS2pIZUdYcUxVK1FvQ3VLZCtuNjZFYVVJZApvNklNL2pJKzZzQ1NHLzV2RVg2M1gxcVpkUWUycFZBSVU1bGdNckhTbzRMZU9VOTJLNVk2OFNyajh4TmlwTkdBCkJVcjRZUlhBZUNmYnN0ODgzNlpVb1FLQmdFRDkxZ29XakRybXlxKyttYUZQOHlMODRwbHgzOHA0RUVDeE4wK2EKeXVqZmVQZldCUW9iWDY1NjlUaklKZmR3d013R0xPME9uZFpLKzIyVlhkNEFnN0o1RUwyejcxUjRrK3hVT3JPcwpEU0MvUTVUMDRlZmFvdFVHZmpvcXhtQmZXbjhtbWdyOFJsMTQvT2hwOTBzQStKdWJkQmc2WVhjeTRPTU1OajVzCkcvODlBb0dCQUt0b29EV29sVytPTnFwMnhwcEtEVGU2RlFGaDRRNGFzQ1E3b01DZG4rZHRuU1Npa1BnRHNiYUkKa1NoSjd1d3NCYWlZUVlncE9GVUx4OHY5WitoRUxLcXIvazJOaVczZFZ6ZHpWZVZMbUJIV1FHZ0FUUmhZMTJCUwp0NnJQMHM5RVZQNU1oQ0NjZTh5dmtJaHZUM0xoVXMyTHZNWTdoZzl2blRrVFZ2UkVBdFlCCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http2-backend
  template:
    metadata:
      labels:
        app: http2-backend
        version: latest
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: service-c
      containers:
      - name: nodejs-http2
        image: mrjonleek/nodejs-http2:v1
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: service-c-secret
          mountPath: "/usr/src/app/certs"
          readOnly: true
      volumes:
      - name: service-c-secret
        secret:
          secretName: service-c-secret
